### ISSUE TITLE
GET /entries

### ISSUE THREAD

**Issue by ernestbrixx** [Ernest2026/diaryApp-backend#8]

**Comment by adophilus** [comment]
We have some potential candidates for the structure of the endpoints:
- Resource-based structure: `/entries`, `/entries/{entryId}`
  - This would mean that entries for a user would have to be fetched using something like this:
    ```
    GET /entries?userId={userId}
    GET /entries/{entryId}?userId={userId}
    ```
    Or we could make it such that the entries gotten from an endpoint are only the ones that belong to the user hitting up the endpoint.
    ```
    GET /entries
    GET /entries/{entryId}
    ```

- Owner-based structure: `/users/{userId}/entries`, `/users/{userId}/entries/{entryId}`
  - This would mean that the entries gotten automatically belong to the user with a corresponding `userId`
    ```
    GET /users/{userId}/entries
    GET /users/{userId}/entries/{entryId}
    ```

**Comment by adophilus** [comment]
Alright so resource based but the 2nd option
